
" Dashboard-VAT metrics"

# I.Function for Dashboard ------------------------------------------------------------------
VAT_sectors_revenues_fun <- function(forecast_combined_cpa_selected,
                                     SimulationYear) {
  
  # Chart 1. Breakdown of VAT Revenues by Sector, Generated by Households -----------------------------------------------------------------
 
              vat_nace_hh_plt <- plot_ly(forecast_combined_cpa_selected) %>%
                                  add_trace(
                                    x = ~PRODUCT_INDUSTRY_CODE, 
                                    y = ~Households_VAT, 
                                    type = 'bar', 
                                    name = ~scenario, # Use the Scenario column to label traces
                                    text = "", # Do not display text inside bars
                                    hoverinfo = 'text', # Show hover text
                                    #hovertext = ~paste(PRODUCT_INDUSTRY_NAME, "<br>scenario:", scenario), # Display PRODUCT_INDUSTRY_NAME and scenario on hover
                                    hovertext = ~paste(PRODUCT_INDUSTRY_NAME, 
                                                       "<br>VAT Value:", round(Total_VAT, 1) # Round the values to 1 decimal place
                                    ), 
                                    showlegend = TRUE
                                  ) %>%
                                  layout(
                                    title = list(
                                      text = paste("Breakdown of VAT Revenues by Sector, Generated by Households,", SimulationYear), 
                                      x = 0.5, # Center the title
                                      y = 0.95, # Adjust vertical position (optional)
                                      font = list(size = 14) # Adjust font size
                                    ),
                                    xaxis = list(
                                      title = '', 
                                      tickangle = -90, # Tilt x-axis labels for better readability
                                      tickfont = list(size = 11) # Set smaller font size for x-axis labels
                                    ), 
                                    yaxis = list(title = ''),
                                    legend = list(x = 0.9, y = 0.99),
                                    barmode = 'group', # Group the bars by Scenario
                                    annotations = list(
                                      list(
                                        x = -0.05,
                                        y = -0.13,
                                        text = "Source: WB staff estimation", # Add your source text
                                        showarrow = FALSE, # Ensure no arrow is shown
                                        xref = "paper",    # Position relative to the chart
                                        yref = "paper",    
                                        xanchor = "left",  # Align the text to the left
                                        yanchor = "top",   
                                        font = list(size = 8) # Adjust font size for annotation
                                      )
                                    )
                                  )
  
  
  # Render the plot
 # vat_nace_hh_plt
  
  
  # Chart 2. VAT GAP Comparison (in LCU Millions)  -----------------------------------------------------------------
  
  
  # forecast_combined_cpa_selected <- forecast_combined_cpa %>%
  #   dplyr::filter(year == SimulationYear) %>%
  #   dplyr::mutate(PRODUCT_INDUSTRY_CODE = factor(PRODUCT_INDUSTRY_CODE, levels = custom_order)) %>%
  #   dplyr::arrange(PRODUCT_INDUSTRY_CODE)
  # 
  
  vat_nace_businesses_plt <- plot_ly(forecast_combined_cpa_selected) %>%
                          add_trace(
                            x = ~PRODUCT_INDUSTRY_CODE, 
                            y = ~Businesses_VAT, 
                            type = 'bar', 
                            name = ~scenario, # Use the Scenario column to label traces
                            text = "", # Do not display text inside bars
                            hoverinfo = 'text', # Show hover text
                            #hovertext = ~paste(PRODUCT_INDUSTRY_NAME, "<br>scenario:", scenario), # Display PRODUCT_INDUSTRY_NAME and scenario on hover
                            hovertext = ~paste(PRODUCT_INDUSTRY_NAME, 
                                               "<br>VAT Value:", round(Total_VAT, 1) # Round the values to 1 decimal place
                            ), 
                            showlegend = TRUE
                          ) %>%
                          layout(
                            title = list(
                              text = paste("Breakdown of VAT revenues by Sector, Generated by Businesses,", SimulationYear), 
                              x = 0.5, # Center the title
                              y = 0.95, # Adjust vertical position (optional)
                              font = list(size = 14) # Adjust font size
                            ),
                            xaxis = list(
                              title = '', 
                              tickangle = -90, # Tilt x-axis labels for better readability
                              tickfont = list(size = 11) # Set smaller font size for x-axis labels
                            ), 
                            yaxis = list(title = ''),
                            legend = list(x = 0.9, y = 0.99),
                            barmode = 'group', # Group the bars by Scenario
                            annotations = list(
                              list(
                                x = -0.05,
                                y = -0.13,
                                text = "Source: WB staff estimation", # Add your source text
                                showarrow = FALSE, # Ensure no arrow is shown
                                xref = "paper",    # Position relative to the chart
                                yref = "paper",    
                                xanchor = "left",  # Align the text to the left
                                yanchor = "top",   
                                font = list(size = 8) # Adjust font size for annotation
                              )
                            )
                          )
  
  
  
  # vat_nace_businesses_plt <- plot_ly(vat_nace_tbl_businesses_combined) %>%
  #                   add_trace(
  #                     x = ~PRODUCT_INDUSTRY_CODE, 
  #                     y = ~Total_Revenues_from_Intermediate_Inputs, 
  #                     type = 'bar', 
  #                     name = ~Scenario, # Use the Scenario column to label traces
  #                     text = ~paste(PRODUCT_INDUSTRY_NAME, "<br>Scenario:", Scenario), # Add PRODUCT_INDUSTRY_NAME and Scenario as hover text
  #                     hoverinfo = 'text', # Show hover text
  #                     showlegend = TRUE # Retain legend
  #                   ) %>%
  #                   layout(
  #                     title = list(
  #                       text = paste("Breakdown of VAT revenues by Sector, Generated by Businesses,", simulation_start_year_VAT), 
  #                       x = 0.5, # Center the title
  #                       y = 0.95, # Adjust vertical position (optional)
  #                       font = list(size = 14) # Adjust font size
  #                     ),
  #                     xaxis = list(
  #                       title = '', 
  #                       tickangle = -90, # Tilt x-axis labels for better readability
  #                       tickfont = list(size = 11) # Set smaller font size for x-axis labels
  #                     ), 
  #                     yaxis = list(title = ''),
  #                     legend = list(x = 0.9, y = 0.99),
  #                     barmode = 'group', # Group the bars by Scenario
  #                     annotations = list(
  #                       list(
  #                         x = -0.05,
  #                         y = -0.13,
  #                         text = "Source: WB staff estimation", # Add your source text
  #                         showarrow = FALSE, # Ensure no arrow is shown
  #                         xref = "paper",    # Position relative to the chart
  #                         yref = "paper",    
  #                         xanchor = "left",  # Align the text to the left
  #                         yanchor = "top",   
  #                         font = list(size = 8) # Adjust font size for annotation
  #                       )
  #                     )
  #                   )
                  
 
  
  # Chart 3.Breakdown of VAT Revenues by Sector, Generated by Households-------------------------------------------------------------------------
  
  vat_nace_NPISH_plt <- plot_ly(forecast_combined_cpa_selected) %>%
                        add_trace(
                          x = ~PRODUCT_INDUSTRY_CODE, 
                          y = ~NPISH_VAT, 
                          type = 'bar', 
                          name = ~scenario, # Use the Scenario column to label traces
                          text = "", # Do not display text inside bars
                          hoverinfo = 'text', # Show hover text
                          #hovertext = ~paste(PRODUCT_INDUSTRY_NAME, "<br>scenario:", scenario), # Display PRODUCT_INDUSTRY_NAME and scenario on hover
                          hovertext = ~paste(PRODUCT_INDUSTRY_NAME, 
                                             "<br>VAT Value:", round(Total_VAT, 1) # Round the values to 1 decimal place
                          ), 
                          showlegend = TRUE
                        ) %>%
                        layout(
                          title = list(
                            text = paste("Breakdown of VAT Revenues by Sector, NPISHs,", SimulationYear), 
                            x = 0.5, # Center the title
                            y = 0.95, # Adjust vertical position (optional)
                            font = list(size = 14) # Adjust font size
                          ),
                          xaxis = list(
                            title = '', 
                            tickangle = -90, # Tilt x-axis labels for better readability
                            tickfont = list(size = 11) # Set smaller font size for x-axis labels
                          ), 
                          yaxis = list(title = ''),
                          legend = list(x = 0.9, y = 0.99),
                          barmode = 'group', # Group the bars by Scenario
                          annotations = list(
                            list(
                              x = -0.05,
                              y = -0.13,
                              text = "Source: WB staff estimation", # Add your source text
                              showarrow = FALSE, # Ensure no arrow is shown
                              xref = "paper",    # Position relative to the chart
                              yref = "paper",    
                              xanchor = "left",  # Align the text to the left
                              yanchor = "top",   
                              font = list(size = 8) # Adjust font size for annotation
                            )
                          )
                        )
                      
  
  # vat_nace_hh_plt <- plot_ly(vat_nace_tbl_hh_combined) %>%
  #                 add_trace(
  #                   x = ~PRODUCT_INDUSTRY_CODE, 
  #                   y = ~Final_Demand_HH, 
  #                   type = 'bar', 
  #                   name = ~Scenario, # Use the Scenario column to label traces
  #                   text = ~paste(PRODUCT_INDUSTRY_NAME, "<br>Scenario:", Scenario), # Add PRODUCT_INDUSTRY_NAME and Scenario as hover text
  #                   hoverinfo = 'text', # Show hover text
  #                   showlegend = TRUE # Retain legend
  #                 ) %>%
  #                 layout(
  #                   title = list(
  #                     text = paste("Breakdown of VAT Revenues by Sector, Generated by Households,", simulation_start_year_VAT), 
  #                     x = 0.5, # Center the title
  #                     y = 0.95, # Adjust vertical position (optional)
  #                     font = list(size = 14) # Adjust font size
  #                   ),
  #                   xaxis = list(
  #                     title = '', 
  #                     tickangle = -90, # Tilt x-axis labels for better readability
  #                     tickfont = list(size = 11) # Set smaller font size for x-axis labels
  #                   ), 
  #                   yaxis = list(title = ''),
  #                   legend = list(x = 0.9, y = 0.99),
  #                   barmode = 'group', # Group the bars by Scenario
  #                   annotations = list(
  #                     list(
  #                       x = -0.05,
  #                       y = -0.13,
  #                       text = "Source: WB staff estimation", # Add your source text
  #                       showarrow = FALSE, # Ensure no arrow is shown
  #                       xref = "paper",    # Position relative to the chart
  #                       yref = "paper",    
  #                       xanchor = "left",  # Align the text to the left
  #                       yanchor = "top",   
  #                       font = list(size = 8) # Adjust font size for annotation
  #                     )
  #                   )
  #                 )
                          
  # Chart 4. Breakdown of VAT by Sector ---------------------------------------------------------------
  
  vat_nace_gov_plt <- plot_ly(forecast_combined_cpa_selected) %>%
    add_trace(
      x = ~PRODUCT_INDUSTRY_CODE, 
      y = ~Households_VAT, 
      type = 'bar', 
      name = ~scenario, # Use the Scenario column to label traces
      text = "", # Do not display text inside bars
      hoverinfo = 'text', # Show hover text
      #hovertext = ~paste(PRODUCT_INDUSTRY_NAME, "<br>scenario:", scenario), # Display PRODUCT_INDUSTRY_NAME and scenario on hover
      hovertext = ~paste(PRODUCT_INDUSTRY_NAME, 
                         "<br>VAT Value:", round(Total_VAT, 1) # Round the values to 1 decimal place
      ), 
      showlegend = TRUE
    ) %>%
    layout(
      title = list(
        text = paste("Breakdown of VAT Revenues by Sector, Generated by Government,", SimulationYear), 
        x = 0.5, # Center the title
        y = 0.95, # Adjust vertical position (optional)
        font = list(size = 14) # Adjust font size
      ),
      xaxis = list(
        title = '', 
        tickangle = -90, # Tilt x-axis labels for better readability
        tickfont = list(size = 11) # Set smaller font size for x-axis labels
      ), 
      yaxis = list(title = ''),
      legend = list(x = 0.9, y = 0.99),
      barmode = 'group', # Group the bars by Scenario
      annotations = list(
        list(
          x = -0.05,
          y = -0.13,
          text = "Source: WB staff estimation", # Add your source text
          showarrow = FALSE, # Ensure no arrow is shown
          xref = "paper",    # Position relative to the chart
          yref = "paper",    
          xanchor = "left",  # Align the text to the left
          yanchor = "top",   
          font = list(size = 8) # Adjust font size for annotation
        )
      )
    )
  
  # 
  # 
  # 
  # 
  # vat_nace_gov_plt <- plot_ly(vat_nace_tbl_gov_combined) %>%
  #                   add_trace(
  #                     x = ~PRODUCT_INDUSTRY_CODE, 
  #                     y = ~Final_Demand_Government, 
  #                     type = 'bar', 
  #                     name = ~Scenario, # Use the Scenario column to label traces
  #                     text = ~paste(PRODUCT_INDUSTRY_NAME, "<br>Scenario:", Scenario), # Add PRODUCT_INDUSTRY_NAME and Scenario as hover text
  #                     hoverinfo = 'text', # Show hover text
  #                     showlegend = TRUE # Retain legend
  #                   ) %>%
  #                   layout(
  #                     title = list(
  #                       text = paste("Breakdown of VAT Revenues by Sector, Generated by Government,", simulation_start_year_VAT), 
  #                       x = 0.5, # Center the title
  #                       y = 0.95, # Adjust vertical position (optional)
  #                       font = list(size = 14) # Adjust font size
  #                     ),
  #                     xaxis = list(
  #                       title = '', 
  #                       tickangle = -90, # Tilt x-axis labels for better readability
  #                       tickfont = list(size = 11) # Set smaller font size for x-axis labels
  #                     ), 
  #                     yaxis = list(title = ''),
  #                     legend = list(x = 0.9, y = 0.99),
  #                     barmode = 'group', # Group the bars by Scenario
  #                     annotations = list(
  #                       list(
  #                         x = -0.05,
  #                         y = -0.13,
  #                         text = "Source: WB staff estimation", # Add your source text
  #                         showarrow = FALSE, # Ensure no arrow is shown
  #                         xref = "paper",    # Position relative to the chart
  #                         yref = "paper",    
  #                         xanchor = "left",  # Align the text to the left
  #                         yanchor = "top",   
  #                         font = list(size = 8) # Adjust font size for annotation
  #                       )
  #                     )
  #                   )
  
  # Export Charts -----------------------------------------------------------
  list(
    # Charts
    vat_nace_hh_plt=vat_nace_hh_plt,
    vat_nace_businesses_plt=vat_nace_businesses_plt,
    vat_nace_NPISH_plt=vat_nace_NPISH_plt,
    vat_nace_gov_plt=vat_nace_gov_plt
    
  )
}


